from app.schemas.book_schema import Book

fake_books: list[Book] = [
    {
        "id": 1,
        "title": "The Silent Patient",
        "desc": "A psychological thriller about a woman who shoots her husband and then stops speaking",
        "author": "Alex Michaelides",
        "publisher": "Celadon Books",
        "published_date": "2019-02-05",
        "page_count": 336,
        "language": "English",
        "genre": "Mystery",
        "average_rating": 4.5,
        "price": 12.99,
        "currency": "USD",
        "tags": ["bestseller", "award-winning"],
        "edition": "First Edition",
    },
    {
        "id": 2,
        "title": "Dune",
        "desc": "A science fiction masterpiece about politics, religion, and power on a desert planet",
        "author": "Frank Herbert",
        "publisher": "Chilton Books",
        "published_date": "1965-08-01",
        "page_count": 412,
        "language": "English",
        "genre": "Science Fiction",
        "average_rating": 4.8,
        "price": 15.50,
        "currency": "USD",
        "tags": ["classic", "sci-fi"],
        "edition": "Anniversary Edition",
    },
    {
        "id": 3,
        "title": "El amor en los tiempos del cólera",
        "desc": "A romantic novel about enduring love over decades",
        "author": "Gabriel García Márquez",
        "publisher": "Vintage Español",
        "published_date": "1985-03-12",
        "page_count": 368,
        "language": "Spanish",
        "genre": "Romance",
        "average_rating": 4.7,
        "price": 14.25,
        "currency": "EUR",
        "tags": ["classic", "literature"],
        "edition": None,
    },
    {
        "id": 4,
        "title": "Le Petit Prince",
        "desc": "A poetic tale about a young prince who travels the universe",
        "author": "Antoine de Saint-Exupéry",
        "publisher": "Reynal & Hitchcock",
        "published_date": "1943-04-06",
        "page_count": 96,
        "language": "French",
        "genre": "Fiction",
        "average_rating": 4.9,
        "price": 9.99,
        "currency": "EUR",
        "tags": ["children", "philosophy"],
        "edition": "Illustrated Edition",
    },
    {
        "id": 5,
        "title": "Die Verwandlung",
        "desc": "A story about a man who wakes up transformed into a giant insect",
        "author": "Franz Kafka",
        "publisher": "Kurt Wolff Verlag",
        "published_date": "1915-10-15",
        "page_count": 201,
        "language": "German",
        "genre": "Horror",
        "average_rating": 4.3,
        "price": 11.75,
        "currency": "EUR",
        "tags": ["classic", "existential"],
        "edition": "Reissue",
    },
    {
        "id": 6,
        "title": "Atomic Habits",
        "desc": "A guide to building good habits and breaking bad ones",
        "author": "James Clear",
        "publisher": "Penguin Random House",
        "published_date": "2018-10-16",
        "page_count": 320,
        "language": "English",
        "genre": "Self Help",
        "average_rating": 4.6,
        "price": 16.99,
        "currency": "USD",
        "tags": ["productivity", "psychology"],
        "edition": "Paperback",
    },
    {
        "id": 7,
        "title": "Sapiens",
        "desc": "A brief history of humankind",
        "author": "Yuval Noah Harari",
        "publisher": "Harper",
        "published_date": "2011-02-10",
        "page_count": 443,
        "language": "English",
        "genre": "History",
        "average_rating": 4.7,
        "price": 18.50,
        "currency": "USD",
        "tags": ["anthropology", "science"],
        "edition": "Updated Edition",
    },
    {
        "id": 8,
        "title": "The Midnight Library",
        "desc": "A novel about a library between life and death with infinite possibilities",
        "author": "Matt Haig",
        "publisher": "Canongate Books",
        "published_date": "2020-08-13",
        "page_count": 304,
        "language": "English",
        "genre": "Fantasy",
        "average_rating": 4.2,
        "price": 13.99,
        "currency": "USD",
        "tags": ["fiction", "life choices"],
        "edition": None,
    },
]
